# Use the official MySQL 5.6 image as the base image
FROM mysql:5.6

# Set environment variables for MySQL
ENV MYSQL_DATABASE=${MYSQL_DATABASE} \
    MYSQL_USER=${MYSQL_USER} \
    MYSQL_PASSWORD=${MYSQL_PASSWORD} \
    MYSQL_RANDOM_ROOT_PASSWORD='true'

# Copy initialization scripts to the docker-entrypoint-initdb.d directory
COPY ./dev/docker/init.db /docker-entrypoint-initdb.d
# Define a volume for MySQL data
VOLUME ["/var/lib/mysql"]

